[position.left_hand]
little = "KEY_A"
ring = "KEY_W"
middle = "KEY_E"
index = "KEY_F"
thumb = "KEY_SPACE"

[position.right_hand]
thumb = "KEY_RIGHT_ALT"
index = "KEY_K"
middle = "KEY_O"
ring = "KEY_P"
little = "KEY_APOSTROPHE"
